# Generated by Django 3.0.8 on 2020-11-06 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='archivos/imagenes')),
                ('carnet', models.FileField(blank=True, null=True, upload_to='archivos/carnet')),
                ('nombres', models.CharField(max_length=80, verbose_name='Nombres')),
                ('raza', models.CharField(max_length=50, verbose_name='Raza')),
                ('edad', models.PositiveIntegerField(default=0, verbose_name='Edad')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('esterilizada_castrado', models.BooleanField(default=False, verbose_name='Esterilizada/Castrado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dueno', models.CharField(max_length=80, verbose_name='Nombre del Dueño')),
                ('rut_dueno', models.CharField(max_length=80, unique=True, verbose_name='Rut del Dueño')),
                ('direccion_dueno', models.CharField(max_length=80, verbose_name='Direccion del Dueño')),
                ('telefono_fijo', models.PositiveIntegerField(default=0, verbose_name='Telefono Fijo')),
                ('celular', models.PositiveIntegerField(default=0, verbose_name='Celular')),
                ('telefono_alternativo', models.PositiveIntegerField(default=0, verbose_name='Telefono Alternativo')),
            ],
            options={
                'verbose_name': 'Dueño',
                'verbose_name_plural': 'Dueños',
                'db_table': 'dueno',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Peluqueria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hipersensibilidad', models.BooleanField(blank=True, default=False, null=True, verbose_name='Hipersensibilidad')),
                ('otitis', models.BooleanField(blank=True, default=False, null=True, verbose_name='Otitis')),
                ('ulceras_ojos', models.BooleanField(blank=True, default=False, null=True, verbose_name='Ulcera Ojos')),
                ('alergias', models.CharField(blank=True, max_length=80, null=True, verbose_name='Alergias')),
                ('premios', models.CharField(max_length=80, verbose_name='Premios')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
            options={
                'verbose_name': 'Peluquería',
                'verbose_name_plural': 'Peluquerías',
                'db_table': 'peluqueria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_veterinario', models.CharField(max_length=80, verbose_name='Nombre del Veterinario')),
                ('telefono_veterinario', models.PositiveIntegerField(default=0, verbose_name='Telefono del Veterinario')),
                ('direccion_veterinario', models.CharField(max_length=80, verbose_name='Direccion del Veterinario')),
                ('fecha_ultimo_celo', models.DateField(verbose_name='Fecha de ultimo celo')),
                ('enfermedades', models.CharField(max_length=80, verbose_name='Enfermedades')),
                ('medicamentos', models.CharField(max_length=80, verbose_name='Medicamentos')),
                ('tolerancia_al_ejercicio', models.CharField(max_length=80, verbose_name='Tolerancia al Ejercicio')),
                ('alimento', models.CharField(max_length=80, verbose_name='Alimento')),
                ('frecuencia_alimentacion', models.CharField(max_length=80, verbose_name='Frecuencia de Alimentación')),
                ('descripcion_del_caracter', models.CharField(max_length=80, verbose_name='Descripción del Caracter')),
                ('fobias_miedos', models.CharField(blank=True, max_length=80, null=True, verbose_name='Fobias o Miedos')),
                ('alergias_alimentos', models.CharField(blank=True, max_length=80, null=True, verbose_name='Alergias a alimentos?')),
                ('alergias_medicamentos', models.CharField(blank=True, max_length=80, null=True, verbose_name='Alergias a medicamentos?')),
                ('alergias_insectos', models.CharField(blank=True, max_length=80, null=True, verbose_name='Alergias a insectos?')),
                ('vacuna_octuple', models.DateField(blank=True, null=True, verbose_name='Vacuna Octuple')),
                ('vacuna_ar', models.DateField(blank=True, null=True, verbose_name='Vacuna AR')),
                ('vacuna_kc', models.DateField(blank=True, null=True, verbose_name='Vacuna KC')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
            options={
                'verbose_name': 'Huesped',
                'verbose_name_plural': 'Huespedes',
                'db_table': 'huesped',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='dueno',
            field=models.ManyToManyField(to='core.Dueno'),
        ),
    ]
